config/routes.rb
Splurty::Application.routes.draw do

  root 'quotes#index'
  resources :quotes
  get 'about', :to => 'quotes#about'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
	validates :saying, :presence => true, :length => { :maximum => 140, :minimum => 3 }
	validates :author, :presence => true, :length => { :maximum => 140, :minimum => 3 }


	def unique_tag
		abbr = []
		self.author.split(" ").each do |sub_string|
			abbr << sub_string[0]
		end

		abbr.join + '#' + self.id.to_s
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	def index
		@quote = Quote.order("RANDOM()").first
	end

	

	def create
		@quote = Quote.create(quote_params)
		if @quote.invalid?
			flash[:error] = '<strong>Could not save</strong> the data you entered is invalid'
		end
		redirect_to root_path
	end

	def about
	end

	def show
		@quote = Quote.where(:id => params[:id]).first
		if @quote.blank?
			render :text => "Not Found", :status => :not_found
		end
	end

	private

	def quote_params
		params.require(:quote).permit(:saying, :author)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <title>Splurty</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div class="col-xs-3">
			<%= link_to root_path, :class => 'logo' do %>
			  <div class="circle">
                <br />
                CODE
                <br />
                RINSE
                <br />
                REPEAT
              </div>
            <% end %>
		</div>
		<div class="col-sm-4 hidden-xs slogan">
			Splurting out unsolicited advice about everything and nothing since 2015"
		</div>
		<div class="col-xs-8 col-xs-offset-1 col-sm-offset-0 col-sm-5 links">
			<!-- Button trigger modal -->
            <%= link_to 'Contribute', '#', :data => {:toggle => 'modal', :target => '#myModal'} %>
            &nbsp;&nbsp;   
			<%= link_to 'About', about_path %>
		</div>
	</header>

	

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel"> Contribute Your Quote</h4>
        </div>
        <%= simple_form_for Quote.new do |f| %>
        <div class="modal-body">
	      <%= f.input :saying, :label => "What's the quote?", :placeholder => "I am the one who knocks!" %>
	      <%= f.input :author, :label => "Who said it?", :placeholder => "Walter White" %>
	      </div>
	      <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        <%= f.submit 'Create', :class => 'btn btn-danger' %>
	      </div>
	    <% end %>
        
      
      </div>
    </div>
  </div>


	<hr />
	<br class="clear" />

	<div class="container">
		<% if flash[:error].present? %>
		  <div class="col-xs-10 col-xs-offset-1 alert alert-danger">
			<%= flash[:error].html_safe %>
		  </div>
		<% end %>

		<%= yield %>
	</div>

<div class="footer">
	<div class="container">
		<div class="col-xs-12 col-sm-6">
			<%= link_to "This isn't enough, I need more", root_path, :class => 'next-quote' %>
		</div>
		<div class="col-xs-12 col-sm-6 footer-blurb">
			Proudly hacked in San Jose, CA by <a href="http://shaunshapiro.neocities.org">Shaun Shapiro</a><br />
			Want to build your own Splurty Web App - <a href="http://thefirehoseproject.com">Learn how to code here</a>
		</div>
	</div>
</div>

</body>
</html>

app/views/quotes/about.html.erb
<div class="col-xs-10 col-xs-offset-1 about">
	<h1 class="text-center">About Splurty</h1>

	<p class="text-center"> 
		This site was built by Shaun Shapiro, as a student project for <a target="_blank" href="http://www.thefirehoseproject.com">theFirehoseProject.</a>
	</p>
	<br />

	<div class="col-xs-12 col-sm-4" style="padding-top:100px;">
		<%= image_tag 'shaun.jpg', :class => 'img_responsive center-block' %>
	</div>

	<div class="col-xs-12 col-sm-7 col-sm-offset-1" style="padding-top:100px;">
		<h2 class="text-center">Shaun Shapiro</h2>
		<br />

	    <p>
		  Shaun is an aspiring web developer with a desire to impact the fields he cares about most. He resides and works in San Jose, CA and holds a bachelor's degree in civil engineering from Santa Clara University. When he is not learning to code in his spare nights and weekends, he enjoys lifting heavy things in the gym, cooking/enjoying food, videogames, and a good Netflix binge. He also enjoys long walks on the beach and lol jk.
	    </p>
    </div>
</div>

<br class="clear" />
<br />
<br />
<br />

app/views/quotes/index.html.erb
<h2>
	<span>SPLURTY / <%= @quote.unique_tag %></span>
	Here's the <u> best (and worst) unsolicited  advice </u> you can get!
</h2>

<h1> <%= @quote.saying %></h1>
<h2 class="pull-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />

app/views/quotes/show.html.erb
<h2>
	<span>SPLURTY / <%= @quote.unique_tag %></span>
	Here's the <u> best (and worst) unsolicited  advice </u> you can get!
</h2>

<h1> <%= @quote.saying %></h1>
<h2 class="pull-right">- <%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />